//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.09 at 03:49:08 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kpmg.in/iocl/api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.kpmg.iocl.api;
